### ISSUE TITLE
Allow to write queries in plain javascript

### ISSUE THREAD

**Issue by maestrow** [discoveryjs/jora#14]
Jora is brief and thus lack some javascript features. It would be very convenient to allow plain javascript (even without intellisense) to query source data.

**Comment by lahmatiy** [comment]
Adding support for JavaScript fragments in jora queries isn't good idea. Reasons:
- Parsing will become too complex and tricky, because of complicated JavaScript syntax. Even if we just collect JavaScript parts as a sequence of chars.
- It's hard to understand that JavaScript is valid until its compilation (or we need to bring JavaScript parser in jora). So JavaScript fragments compilation introduces potential exceptions on query compilation phase rather than on parse phase.
- I intent to implement interpreter mode, when no code compilation is involved. It may be useful for features like debugging and step-by-step evaluation. Currently jora queries are translating to JavaScript and then exposing it as functions. It may be a problem for environments where code compilation is prohibited (due to CSP or related). Introducing JavaScript fragments makes impossible to avoid runtime compilation.
- Compilation of JavaScript fragments may to be a challenge itself. Because it require correct isolation, to prevent reference leakage, name collision and so on. Also such code may to be a source of security issues, globals pollution, you can send network requests etc. Currently jora queries have no access to something outside a query definitions and values passed to it. It's like a pure function actually, all data transformations in jora are happen in immutable way. With JavaScript fragments we can't guarantee that.
There are two ways to break all the things at the moment: extra functions (methods) passed in query config and data that contain accessors and/or methods. These external pieces of code may mutate data or do something bad. However, they are have no influence on query parsing and compilation, is using on query evaluation phase only, and may be moderated (for instance, you can't add extra methods or pass anything except JSON when using web interface).
- Jora is designing to make possible many features as performance optimisations, debugging, input data shape recovery and many more. JavaScript fragments may make most of them much harder or even impossible.

What to do then? It depends on your use cases. If you intent to use jora in your code, you may pass extra methods when create a query to fulfil the lack of functionality. If you would jora has more features, please fill an issue and describe your use case and we will find a solution.

**Comment by lahmatiy** [comment]
Had a look at header one more time, may be I misunderstood your question.
Is it about to write entire query in JavaScript? If so, this question is not to jora itself, but for place where it's using.

**Comment by maestrow** [comment]
Oh, sorry. This suggestion is for https://github.com/discoveryjs/browser-extension-json-discovery
