### ISSUE TITLE
Table with values on different levels

### ISSUE THREAD

**Issue by SorryGames** [discoveryjs/jora#29]
Good day! 

First of all, JSON Discovery is powerful tool, it makes me happy today! 
However, example guide for Jora is very poor, so I've created the issue to resolve my case.

JSON data: [here](https://raw.githubusercontent.com/json-schema-org/json-schema-test-suite-npm/master/package-lock.json#report&q=Li52ZXJzaW9u)

I want to show in table the following fields:
- dependency name
- version
- dev

```
acorn          6.1.1     true
acorn-jsx      5.0.1     true
...
```

But I have no idea, how to do table content using fields on different levels of JSON file.

Could you assist me, please? 
Thanks in advance!

**Comment by lahmatiy** [comment]
Thank you for feedback and your question! :)

Let's make your table step by step. First of all we need to get a list of objects. `dependencies` is a dictionary of `name` -> `{ data }`, first of all we need to convert it to an array:

```js
dependencies.entries()
```

This gives us an array of `{ key, value }` elements, so we need convert it into object `{ name: key, ...value}`:

```js
dependencies.entries().({ name: key, ...value })
```

The result will looks like:

```js
[
    { name: "acorn", version: "6.1.1", resolved: "...", integrity: "...", dev: true },
    ...
]
```

Now we need to change view from "default" to "custom" and describe a table or just click on "Table" view preset:

![image](https://user-images.githubusercontent.com/270491/118849459-0e721d00-b8d0-11eb-82c1-89305ec8d69d.png)

However, you need just 3 specific columns. There are 2 ways to achieve that: on data and on view level.

On data level we need to transform objects so that they contain only the required fields:

```js
dependencies.entries().({ name: key, version: value.version, dev: value.dev })
// or
dependencies.entries().({ name: key, ...value }).({ name, version, dev })
```

But it is better to do this at the presentation level. To do this, we need to define the columns we need:

```js
{
    view: 'table',
    cols: ['name', 'version', 'dev']
}
```

Keep in mind that in example above I used shorthands for column definition, but there are more options:

```js
{
    view: 'table',
    cols: [
        'name',
        {
            header: 'Version',
            data: 'version'
        },
        {
            header: 'Dev',
            content: [
                'checkbox{ checked: dev, readonly: true }'
            ]
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/270491/118853211-cead3480-b8d3-11eb-86f4-d0732ab35a54.png)

You also may overload some of columns and left others as is:

![image](https://user-images.githubusercontent.com/270491/118852873-7413d880-b8d3-11eb-85e4-36721fb57c49.png)

That's it – [your table](https://raw.githubusercontent.com/json-schema-org/json-schema-test-suite-npm/master/package-lock.json#report&dzen&q=ZGVwZW5kZW5jaWVzLmVudHJpZXMoKS4oeyBuYW1lOiBrZXksIC4uLnZhbHVlIH0p&v=ewogICAgdmlldzogJ3RhYmxlJywKICAgIGNvbHM6IFsKICAgICAgICAnbmFtZScsCiAgICAgICAgewogICAgICAgICAgICBoZWFkZXI6ICdWZXJzaW9uJywKICAgICAgICAgICAgZGF0YTogJ3ZlcnNpb24nCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAgIGhlYWRlcjogJ0RldicsCiAgICAgICAgICAgIGNvbnRlbnQ6IFsKICAgICAgICAgICAgICAgICdjaGVja2JveHsgY2hlY2tlZDogZGV2LCByZWFkb25seTogdHJ1ZSB9JwogICAgICAgICAgICBdCiAgICAgICAgfQogICAgXQp9) :)

Just in case:

- View usage examples can be found by the link [Views showcase](https://raw.githubusercontent.com/json-schema-org/json-schema-test-suite-npm/master/package-lock.json#views-showcase:checkbox)
![image](https://user-images.githubusercontent.com/270491/118855009-9dcdff00-b8d5-11eb-8c5a-00dbf1a1eb96.png)

- Editors and everything not related to the presentation can be hidden with those buttons in top right corner:
![image](https://user-images.githubusercontent.com/270491/118853493-1df36500-b8d4-11eb-95a5-854e3dc3ec1f.png)

-----

Yeah, a documentation is still very poor and it's a big problem. Sorry for inconvenience. I believe that sooner or later we will fix it.
